In [1]:
# importer les bibliothèques nécessaires

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
# Les données sont chargées à partir d'un fichier CSV

# Randomizer la graine pour la reproductibilité
np.random.seed(0)

data_size = 20

data = {
    'Country': np.random.choice(['France', 'Spain', 'Germany'], data_size),
    'Age': np.random.randint(25, 50, data_size),
    'Salary': np.random.randint(30000, 90000, data_size),
    'Purchased': np.random.choice(['No', 'Yes'], data_size) # The Target Variable
}
df = pd.DataFrame(data)


# Afficher les premières lignes du DataFrame
display(df.head())

  Country  Age  Salary Purchased
0  France   33   46321        No
1   Spain   34   82489        No
2  France   45   49129        No
3   Spain   44   83887       Yes
4   Spain   41   71504       Yes

In [3]:
# Créer les variables de caractéristiques (X) et la variable cible (y)
X = df.iloc[:, :-1]  # Features

y = df[
    'Purchased'
]

print(y.head())
print(X)

0     No
1     No
2     No
3    Yes
4    Yes
Name: Purchased, dtype: object
    Country  Age  Salary
0    France   33   46321
1     Spain   34   82489
2    France   45   49129
3     Spain   44   83887
4     Spain   41   71504
5   Germany   44   85839
6    France   30   79866
7   Germany   40   48676
8    France   40   87495
9    France   25   61230
10   France   43   41723
11  Germany   28   73890
12    Spain   49   47591
13  Germany   42   85324
14  Germany   44   88146
15   France   44   73136
16    Spain   44   56752
17    Spain   39   89300
18    Spain   32   53605
19    Spain   25   36021

In [4]:
# Machines ne comprends pas les textes comme "France", "Spain", "Germany", "Yes", "No"
# Nous devons les encoder en valeurs numériques
le = LabelEncoder()
y_encoded = le.fit_transform(y)

X_encoded = pd.get_dummies(X, columns=['Country'])

# Afficher drop_first=True pour éviter le piège des variables fictives
display(X_encoded.head())

   Age  Salary  Country_France  Country_Germany  Country_Spain
0   33   46321            True            False          False
1   34   82489           False            False           True
2   45   49129            True            False          False
3   44   83887           False            False           True
4   41   71504           False            False           True

In [7]:
# Ne pas trainer sur tout le dataset pour éviter l'overfitting
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y_encoded, test_size=0.2, random_state=42)

print(f"Total Rows: {len(X_encoded)}")
print(f"Training Rows: {len(X_train)}")
print(f"Testing Rows: {len(X_test)}")

Total Rows: 20
Training Rows: 16
Testing Rows: 4

In [8]:
# Feature Scaling
scaler = StandardScaler()

X_trained_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Convertir les tableaux numpy en DataFrames pour une meilleure lisibilité
X_train_final = pd.DataFrame(X_trained_scaled, columns=X_encoded.columns)

print("--- Scaled Training Features ---")
display(X_train_final.head())
# Notice: L'Age et le Salaire sont maintenant sur une échelle similaire

--- Scaled Training Features ---

        Age    Salary  Country_France  Country_Germany  Country_Spain
0  0.199337  1.235234         1.48324         -0.67420      -0.774597
1  0.730901  1.141520        -0.67420          1.48324      -0.774597
2 -1.395357  0.465322        -0.67420          1.48324      -0.774597
3  0.730901  1.031056        -0.67420         -0.67420       1.290994
4 -0.863792 -0.682614        -0.67420         -0.67420       1.290994

In [9]:
# Vérifier les valeurs manquantes
# Creer un Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier

clf = DecisionTreeClassifier()
clf = clf.fit(X_train_final, y_train)

In [14]:
clf.predict(X_trained_scaled)

/Users/cxnner05/Documents/uni_notes/year 3/lab-ml/.venv/lib/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1])

In [15]:
y_train

array([0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1])