# Lab 4

In [31]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import sklearn

In [32]:
# For this laboratory, there are different datasets that can be used.
# For now, we will use the raw_train dataset, which is the training set without any preprocessing.

path = "./data/raw_train.csv"

df = pd.read_csv(path)

## Data Cleaning

Get information about the dataset

In [33]:
df.head(15)

,quantity,amount,job_category_description,bid_date,total_bid,num_pay_items,pay_item_description,unit_english_id,category_id,category_description,job_id,contractor_id,primary_location,pay_item_id,row_id
0,1.0,7000.0,BRIDGE,2018-01-18,453231.70,55,CONSTRUCTION ENGINEERING,EACH,25,MOBILIZATION,JOB_002829,CON_000015,LOC_000091,ITEM_003580,JOB_002829__CON_000015
1,1.0,11000.0,BRIDGE,2018-01-18,148876.00,20,CONSTRUCTION ENGINEERING,EACH,25,MOBILIZATION,JOB_001298,CON_000015,LOC_000028,ITEM_003580,JOB_001298__CON_000015
2,1.0,24000.0,BRIDGE,2018-01-18,1513003.05,101,CONSTRUCTION ENGINEERING,EACH,25,MOBILIZATION,JOB_001294,CON_000015,LOC_000028,ITEM_003580,JOB_001294__CON_000015
3,1.0,1.0,BRIDGE,2018-01-18,453231.70,55,LIQUIDATED DAMAGES,$,31,ALTERNATES/BONUS/TIME,JOB_002829,CON_000015,LOC_000091,ITEM_003537,JOB_002829__CON_000015
4,1.0,1.0,BRIDGE,2018-01-18,1513003.05,101,LIQUIDATED DAMAGES,$,31,ALTERNATES/BONUS/TIME,JOB_001294,CON_000015,LOC_000028,ITEM_003537,JOB_001294__CON_000015
5,1.0,1.0,BRIDGE,2018-01-18,148876.00,20,LIQUIDATED DAMAGES,$,31,ALTERNATES/BONUS/TIME,JOB_001298,CON_000015,LOC_000028,ITEM_003537,JOB_001298__CON_000015
6,1.0,1.0,BRIDGE,2018-01-18,453231.70,55,CONTRACT LIENS,$,31,ALTERNATES/BONUS/TIME,JOB_002829,CON_000015,LOC_000091,ITEM_001111,JOB_002829__CON_000015
7,1.0,1.0,BRIDGE,2018-01-18,148876.00,20,CONTRACT LIENS,$,31,ALTERNATES/BONUS/TIME,JOB_001298,CON_000015,LOC_000028,ITEM_001111,JOB_001298__CON_000015
8,1.0,1.0,BRIDGE,2018-01-18,1513003.05,101,CONTRACT LIENS,$,31,ALTERNATES/BONUS/TIME,JOB_001294,CON_000015,LOC_000028,ITEM_001111,JOB_001294__CON_000015
9,1.0,1.0,BRIDGE,2018-01-18,453231.70,55,QUALITY ADJUSTMENTS HMA,$,31,ALTERNATES/BONUS/TIME,JOB_002829,CON_000015,LOC_000091,ITEM_001362,JOB_002829__CON_000015
10,1.0,1.0,BRIDGE,2018-01-18,1513003.05,101,QUALITY ADJUSTMENTS HMA,$,31,ALTERNATES/BONUS/TIME,JOB_001294,CON_000015,LOC_000028,ITEM_001362,JOB_001294__CON_000015
11,1.0,1.0,BRIDGE,2018-01-18,453231.70,55,QUALITY ADJUSTMENTS TEMPORARY TRAFFIC CONTROL ...,$,31,ALTERNATES/BONUS/TIME,JOB_002829,CON_000015,LOC_000091,ITEM_001550,JOB_002829__CON_000015
12,1.0,1.0,BRIDGE,2018-01-18,1513003.05,101,QUALITY ADJUSTMENTS TEMPORARY TRAFFIC CONTROL ...,$,31,ALTERNATES/BONUS/TIME,JOB_001294,CON_000015,LOC_000028,ITEM_001550,JOB_001294__CON_000015
13,1.0,1.0,BRIDGE,2018-01-18,148876.00,20,QUALITY ADJUSTMENTS TEMPORARY TRAFFIC CONTROL ...,$,31,ALTERNATES/BONUS/TIME,JOB_001298,CON_000015,LOC_000028,ITEM_001550,JOB_001298__CON_000015
14,1.0,1.0,BRIDGE,2018-01-18,453231.70,55,QUALITY ADJUSTMENTS FAILED MATERIALS,$,31,ALTERNATES/BONUS/TIME,JOB_002829,CON_000015,LOC_000091,ITEM_000697,JOB_002829__CON_000015

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 832056 entries, 0 to 832055
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   quantity                  832056 non-null  float64
 1   amount                    832056 non-null  float64
 2   job_category_description  832056 non-null  object
 3   bid_date                  832056 non-null  object
 4   total_bid                 832056 non-null  float64
 5   num_pay_items             832056 non-null  int64
 6   pay_item_description      832056 non-null  object
 7   unit_english_id           832054 non-null  object
 8   category_id               832056 non-null  int64
 9   category_description      832056 non-null  object
 10  job_id                    832056 non-null  object
 11  contractor_id             832056 non-null  object
 12  primary_location          832056 non-null  object
 13  pay_item_id               832056 non-null  object
 14  row_id                    832056 non-null  object
dtypes: float64(3), int64(2), object(10)
memory usage: 95.2+ MB

There are some null values on the unit_english_id column, which is only rows. We can drop this column without losing any information.

In [35]:
print(df["unit_english_id"].isnull().sum())

# Drop the rows with null values in the unit_english_id column
df = df.dropna(subset=["unit_english_id"])

2

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 832054 entries, 0 to 832055
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   quantity                  832054 non-null  float64
 1   amount                    832054 non-null  float64
 2   job_category_description  832054 non-null  object
 3   bid_date                  832054 non-null  object
 4   total_bid                 832054 non-null  float64
 5   num_pay_items             832054 non-null  int64
 6   pay_item_description      832054 non-null  object
 7   unit_english_id           832054 non-null  object
 8   category_id               832054 non-null  int64
 9   category_description      832054 non-null  object
 10  job_id                    832054 non-null  object
 11  contractor_id             832054 non-null  object
 12  primary_location          832054 non-null  object
 13  pay_item_id               832054 non-null  object
 14  row_id                    832054 non-null  object
dtypes: float64(3), int64(2), object(10)
memory usage: 101.6+ MB

The data for the bid_date is in object. Parse to date

In [37]:
df["bid_date"] = pd.to_datetime(df["bid_date"])

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 832054 entries, 0 to 832055
Data columns (total 15 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   quantity                  832054 non-null  float64
 1   amount                    832054 non-null  float64
 2   job_category_description  832054 non-null  object
 3   bid_date                  832054 non-null  datetime64[ns]
 4   total_bid                 832054 non-null  float64
 5   num_pay_items             832054 non-null  int64
 6   pay_item_description      832054 non-null  object
 7   unit_english_id           832054 non-null  object
 8   category_id               832054 non-null  int64
 9   category_description      832054 non-null  object
 10  job_id                    832054 non-null  object
 11  contractor_id             832054 non-null  object
 12  primary_location          832054 non-null  object
 13  pay_item_id               832054 non-null  object
 14  row_id                    832054 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(2), object(9)
memory usage: 101.6+ MB

Lets check for possible duplicates in the dataset. We can drop them if there are any.

In [38]:
df.duplicated().sum()

np.int64(7998)

Duplicates found. Drop them.

In [39]:
df.drop_duplicates(inplace=True)

Verify that the duplicates have been dropped.

In [40]:
df.duplicated().sum()

np.int64(0)

Another thing that we can check is to verify that the total_bid (the target variable) is not negative and if it is the result of multipying the quantity and the amount. If so, then there is a leakage in the data, and we should drop the total_bid column and use the quantity and amount to calculate the total_bid when needed.

In [41]:
(df["quantity"] * df["amount"] != df["total_bid"]).sum()

np.int64(824056)

## Feature Engineering

Create new columns based on the columns we have.

Separate the bid_date column into year, month and day columns.

In [42]:
df["bid_month"] = df["bid_date"].dt.month
df["bid_year"] = df["bid_date"].dt.year
df["bid_day"] = df["bid_date"].dt.dayofweek

Have aggregate features based.

In [44]:

# Average bid amount per contractor and the total number of bids per contractor
df["supplier_avg_bid"] = df.groupby("contractor_id")["total_bid"].transform("mean")
df["supplier_bid_count"] = df.groupby("contractor_id")["total_bid"].transform("count")

# Average bid amount per unit and the total number of bids per unit
df["unit_avg_bid"] = df.groupby("unit_english_id")["total_bid"].transform("mean")
df["unit_bid_count"] = df.groupby("unit_english_id")["total_bid"].transform("count")

# Supplier's bid frequency this year
df["supplier_bids_this_year"] = df.groupby(["contractor_id", "bid_year"])["row_id"].transform("count")

Preview that the new features have been created correctly.

In [45]:
df.head(15)

,quantity,amount,job_category_description,bid_date,total_bid,num_pay_items,pay_item_description,unit_english_id,category_id,category_description,...,pay_item_id,row_id,bid_month,bid_year,bid_day,supplier_avg_bid,supplier_bid_count,unit_avg_bid,unit_bid_count,supplier_bids_this_year
0,1.0,7000.0,BRIDGE,2018-01-18,453231.70,55,CONSTRUCTION ENGINEERING,EACH,25,MOBILIZATION,...,ITEM_003580,JOB_002829__CON_000015,1,2018,3,1.155074e+06,1575,8.706091e+06,273849,631
1,1.0,11000.0,BRIDGE,2018-01-18,148876.00,20,CONSTRUCTION ENGINEERING,EACH,25,MOBILIZATION,...,ITEM_003580,JOB_001298__CON_000015,1,2018,3,1.155074e+06,1575,8.706091e+06,273849,631
2,1.0,24000.0,BRIDGE,2018-01-18,1513003.05,101,CONSTRUCTION ENGINEERING,EACH,25,MOBILIZATION,...,ITEM_003580,JOB_001294__CON_000015,1,2018,3,1.155074e+06,1575,8.706091e+06,273849,631
3,1.0,1.0,BRIDGE,2018-01-18,453231.70,55,LIQUIDATED DAMAGES,$,31,ALTERNATES/BONUS/TIME,...,ITEM_003537,JOB_002829__CON_000015,1,2018,3,1.155074e+06,1575,4.438728e+06,83020,631
4,1.0,1.0,BRIDGE,2018-01-18,1513003.05,101,LIQUIDATED DAMAGES,$,31,ALTERNATES/BONUS/TIME,...,ITEM_003537,JOB_001294__CON_000015,1,2018,3,1.155074e+06,1575,4.438728e+06,83020,631
5,1.0,1.0,BRIDGE,2018-01-18,148876.00,20,LIQUIDATED DAMAGES,$,31,ALTERNATES/BONUS/TIME,...,ITEM_003537,JOB_001298__CON_000015,1,2018,3,1.155074e+06,1575,4.438728e+06,83020,631
6,1.0,1.0,BRIDGE,2018-01-18,453231.70,55,CONTRACT LIENS,$,31,ALTERNATES/BONUS/TIME,...,ITEM_001111,JOB_002829__CON_000015,1,2018,3,1.155074e+06,1575,4.438728e+06,83020,631
7,1.0,1.0,BRIDGE,2018-01-18,148876.00,20,CONTRACT LIENS,$,31,ALTERNATES/BONUS/TIME,...,ITEM_001111,JOB_001298__CON_000015,1,2018,3,1.155074e+06,1575,4.438728e+06,83020,631
8,1.0,1.0,BRIDGE,2018-01-18,1513003.05,101,CONTRACT LIENS,$,31,ALTERNATES/BONUS/TIME,...,ITEM_001111,JOB_001294__CON_000015,1,2018,3,1.155074e+06,1575,4.438728e+06,83020,631
9,1.0,1.0,BRIDGE,2018-01-18,453231.70,55,QUALITY ADJUSTMENTS HMA,$,31,ALTERNATES/BONUS/TIME,...,ITEM_001362,JOB_002829__CON_000015,1,2018,3,1.155074e+06,1575,4.438728e+06,83020,631
10,1.0,1.0,BRIDGE,2018-01-18,1513003.05,101,QUALITY ADJUSTMENTS HMA,$,31,ALTERNATES/BONUS/TIME,...,ITEM_001362,JOB_001294__CON_000015,1,2018,3,1.155074e+06,1575,4.438728e+06,83020,631
11,1.0,1.0,BRIDGE,2018-01-18,453231.70,55,QUALITY ADJUSTMENTS TEMPORARY TRAFFIC CONTROL ...,$,31,ALTERNATES/BONUS/TIME,...,ITEM_001550,JOB_002829__CON_000015,1,2018,3,1.155074e+06,1575,4.438728e+06,83020,631
12,1.0,1.0,BRIDGE,2018-01-18,1513003.05,101,QUALITY ADJUSTMENTS TEMPORARY TRAFFIC CONTROL ...,$,31,ALTERNATES/BONUS/TIME,...,ITEM_001550,JOB_001294__CON_000015,1,2018,3,1.155074e+06,1575,4.438728e+06,83020,631
13,1.0,1.0,BRIDGE,2018-01-18,148876.00,20,QUALITY ADJUSTMENTS TEMPORARY TRAFFIC CONTROL ...,$,31,ALTERNATES/BONUS/TIME,...,ITEM_001550,JOB_001298__CON_000015,1,2018,3,1.155074e+06,1575,4.438728e+06,83020,631
14,1.0,1.0,BRIDGE,2018-01-18,453231.70,55,QUALITY ADJUSTMENTS FAILED MATERIALS,$,31,ALTERNATES/BONUS/TIME,...,ITEM_000697,JOB_002829__CON_000015,1,2018,3,1.155074e+06,1575,4.438728e+06,83020,631

## Analysis